### ISSUE TITLE
[Enhancement] Automatically convert links

### ISSUE THREAD

**Issue by SupremeDevice** [thevenuz/xify#1]
Hello! Don't know how hard this would be to implement, but is there a way for extensions to get "notified" the clipboard has been changed? The keyboard shortcut is nice but I find myself forgetting what it is lol

**Comment by thevenuz** [comment]
Hello! We can try converting the link on "Ctrl + C" (if it's possible) directly instead of converting it just on the custom shortcut. Will this work for you?

**Comment by SupremeDevice** [comment]
Yes, that would be nice 😄 
I'm on Firefox, any idea when that version will receive an update? I see the version on the chrome store received an update last week vs. over a month on firefox.

**Comment by thevenuz** [comment]
@SupremeDevice the PR #4 should allow users to copy the modified links directly on copy command instead of custom shortcut.

**Comment by thevenuz** [comment]
PR #4 addresses this issue
